# Generated by Django 5.0.8 on 2026-07-20 12:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_rename_cat_lot_med_exp_idx_catalogue_l_medicam_8a7259_idx_and_more"),
        ("fournisseurs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="boncommande",
            new_name="fournisseur_numero_0e1017_idx",
            old_name="bc_numero_idx",
        ),
        migrations.RenameIndex(
            model_name="boncommande",
            new_name="fournisseur_fournis_ace807_idx",
            old_name="bc_fourn_statut_idx",
        ),
        migrations.RenameIndex(
            model_name="boncommande",
            new_name="fournisseur_statut_782396_idx",
            old_name="bc_statut_date_idx",
        ),
        migrations.RenameIndex(
            model_name="fournisseur",
            new_name="fournisseur_code_fdbfb9_idx",
            old_name="fourn_code_idx",
        ),
        migrations.RenameIndex(
            model_name="fournisseur",
            new_name="fournisseur_actif_a3af8a_idx",
            old_name="fourn_actif_nom_idx",
        ),
        migrations.RenameIndex(
            model_name="receptionboncommande",
            new_name="fournisseur_bon_com_770e21_idx",
            old_name="reception_bc_date_idx",
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="date_commande",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="boncommande",
            name="numero",
            field=models.CharField(
                help_text="Séquentiel — généré par le service, jamais saisi.",
                max_length=30,
                unique=True,
                verbose_name="Numéro de bon de commande",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="code",
            field=models.CharField(
                help_text="Identifiant court affiché sur les bons de commande.",
                max_length=20,
                unique=True,
                verbose_name="Code fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="conditions_paiement",
            field=models.CharField(
                blank=True, help_text="Ex. « 30 jours net », « comptant »…", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="ligneboncommande",
            name="quantite_recue",
            field=models.PositiveIntegerField(
                default=0, help_text="Cumul des réceptions successives, ≤ quantite_commandee."
            ),
        ),
        migrations.AlterField(
            model_name="ligneboncommande",
            name="taux_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Taux de TVA (%)",
            ),
        ),
        migrations.AlterField(
            model_name="lignereception",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lot créé (ou complété) par cette réception.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receptions",
                to="catalogue.lot",
            ),
        ),
        migrations.AlterField(
            model_name="receptionboncommande",
            name="date_reception",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="receptionboncommande",
            name="numero_bordereau",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="N° bordereau du fournisseur"
            ),
        ),
    ]
