# Generated by Django 5.0.8 on 2026-08-07 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fournisseurs", "0002_rename_bc_numero_idx_fournisseur_numero_0e1017_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boncommande",
            name="date_commande",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
