# Generated by Django 5.0.8 on 2026-07-20 12:08

import infrastructure.outbox.modeles
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="entreeoutbox",
            name="outbox_type_statut_idx",
        ),
        migrations.RemoveIndex(
            model_name="entreeoutbox",
            name="outbox_cree_le_idx",
        ),
        migrations.RenameIndex(
            model_name="entreeoutbox",
            new_name="idx_outbox_a_traiter",
            old_name="outbox_statut_prochaine_idx",
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="charge_utile",
            field=models.JSONField(
                help_text="Données complètes de l'événement sérialisées en JSON.",
                verbose_name="Charge utile",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="cree_le",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="erreur_message",
            field=models.TextField(
                blank=True,
                help_text="Dernière erreur enregistrée lors du traitement.",
                verbose_name="Message d'erreur",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Identifiant",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="id_objet",
            field=models.UUIDField(
                blank=True,
                help_text="UUID de l'objet métier ayant généré cet événement.",
                null=True,
                verbose_name="Identifiant objet source",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="id_utilisateur",
            field=models.UUIDField(blank=True, null=True, verbose_name="Utilisateur déclencheur"),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="max_tentatives",
            field=models.PositiveSmallIntegerField(default=5, verbose_name="Maximum de tentatives"),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="modele_source",
            field=models.CharField(
                blank=True,
                help_text="Nom du modèle Django source (ex. : 'Vente').",
                max_length=100,
                verbose_name="Modèle source",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="prochaine_tentative",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp UTC de la prochaine tentative (backoff exponentiel).",
                null=True,
                verbose_name="Prochaine tentative",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="statut",
            field=models.CharField(
                choices=[
                    (infrastructure.outbox.modeles.StatutOutbox["EN_ATTENTE"], "En attente"),
                    (
                        infrastructure.outbox.modeles.StatutOutbox["EN_COURS"],
                        "En cours de traitement",
                    ),
                    (infrastructure.outbox.modeles.StatutOutbox["TRAITE"], "Traité avec succès"),
                    (infrastructure.outbox.modeles.StatutOutbox["ECHEC"], "Échec définitif"),
                ],
                db_index=True,
                default=infrastructure.outbox.modeles.StatutOutbox["EN_ATTENTE"],
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="entreeoutbox",
            name="type_evenement",
            field=models.CharField(
                db_index=True,
                help_text="Nom de la classe d'événement (ex. : 'EvenementVenteCreee').",
                max_length=100,
                verbose_name="Type d'événement",
            ),
        ),
    ]
