# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ecriturecomptable",
            new_name="comptabilit_date_ec_232d64_idx",
            old_name="compta_date_idx",
        ),
        migrations.RenameIndex(
            model_name="ecriturecomptable",
            new_name="comptabilit_type_ec_976020_idx",
            old_name="compta_type_date_idx",
        ),
    ]
