# Generated by PharmApp ÉTAPE 02 — Durcissement contraintes comptabilité (2026-08-06)
#
# EcritureComptable.montant : toutes les écritures doivent avoir un montant > 0.
# Le signe (recette/dépense) est porté par le champ type_ecriture, pas le montant.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0002_rename_compta_date_idx_comptabilit_date_ec_232d64_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ecriturecomptable",
            constraint=models.CheckConstraint(
                check=models.Q(montant__gt=0),
                name="chk_ecriture_montant_positif",
                violation_error_message="Le montant d'une écriture comptable doit être strictement positif.",
            ),
        ),
        # Index de performance : requêtes de rapports par type et date
        migrations.AddIndex(
            model_name="ecriturecomptable",
            index=models.Index(
                fields=["type_ecriture", "date_ecriture"],
                name="compta_type_date_idx",
            ),
        ),
    ]
