# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alertestock",
            new_name="stocks_aler_est_res_9ba08b_idx",
            old_name="alerte_resolue_idx",
        ),
        migrations.RenameIndex(
            model_name="alertestock",
            new_name="stocks_aler_medicam_78b039_idx",
            old_name="alerte_med_idx",
        ),
        migrations.RenameIndex(
            model_name="mouvementstock",
            new_name="stocks_mouv_lot_id_07b878_idx",
            old_name="stock_lot_date_idx",
        ),
        migrations.RenameIndex(
            model_name="mouvementstock",
            new_name="stocks_mouv_type_mo_7ffb8c_idx",
            old_name="stock_type_date_idx",
        ),
    ]
