# Generated by PharmApp ÉTAPE 02 — Durcissement contraintes stocks (2026-08-06)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_rename_alerte_resolue_idx_stocks_aler_est_res_9ba08b_idx_and_more"),
        ("catalogue", "0003_rename_cat_lot_med_exp_idx_catalogue_l_medicam_8a7259_idx_and_more"),
    ]

    operations = [
        # ── stocks_mouvement : CHECK quantités avant/après positives ──────────
        # Note : quantite peut être négatif (sorties) — seules avant/après sont
        # contraintes car elles représentent un stock physique.
        migrations.AddConstraint(
            model_name="mouvementstock",
            constraint=models.CheckConstraint(
                check=models.Q(quantite_avant__gte=0),
                name="chk_mouvement_quantite_avant_pos",
                violation_error_message="La quantité avant mouvement ne peut pas être négative.",
            ),
        ),
        migrations.AddConstraint(
            model_name="mouvementstock",
            constraint=models.CheckConstraint(
                check=models.Q(quantite_apres__gte=0),
                name="chk_mouvement_quantite_apres_pos",
                violation_error_message="La quantité après mouvement ne peut pas être négative.",
            ),
        ),
        # ── stocks_mouvement : index effectue_par (traçabilité réglementaire) ─
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["effectue_par", "cree_le"],
                name="stocks_mouv_effectue_par_idx",
            ),
        ),
    ]
