# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0004_vente_alignment_modele_runtime"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="vente",
            new_name="ventes_vent_statut_5cc8a4_idx",
            old_name="vente_statut_idx",
        ),
        migrations.RenameIndex(
            model_name="vente",
            new_name="ventes_vent_vendeur_24f031_idx",
            old_name="vente_vendeur_idx",
        ),
        migrations.RenameIndex(
            model_name="vente",
            new_name="ventes_vent_client__152ebd_idx",
            old_name="vente_client_statut_idx",
        ),
        migrations.RenameIndex(
            model_name="vente",
            new_name="ventes_vent_numero_fb430d_idx",
            old_name="vente_num_idx",
        ),
    ]
