# Generated by PharmApp ÉTAPE 02 — Durcissement des contraintes DB (2026-08-06)
#
# Cette migration ajoute les contraintes CHECK et index manquants identifiés
# lors de l'audit ÉTAPE 02. Elle est ADDITIVE et non destructive.
#
# Contraintes ajoutées :
#   ventes_vente :
#     - CHK_vente_montant_total_positif     : montant_total >= 0
#     - CHK_vente_montant_encaisse_positif  : montant_encaisse >= 0
#     - CHK_vente_montant_rendu_positif     : montant_rendu >= 0
#     - CHK_vente_sous_total_positif        : sous_total >= 0
#     - IDX ventes_vent_cree_le_idx         : cree_le (requêtes de clôture)
#
#   clients_client :
#     - CHK_client_plafond_credit_positif   : plafond_credit >= 0
#     - CHK_client_taux_prise_en_charge     : 0 <= taux_prise_en_charge <= 100
#     - IDX clients_encours_credit_idx      : credit_autorise, est_actif
#
#   stocks_mouvement :
#     - CHK_mouvement_quantite_avant_pos    : quantite_avant >= 0
#     - CHK_mouvement_quantite_apres_pos    : quantite_apres >= 0
#     - IDX stocks_mouv_effectue_par_idx    : effectue_par (traçabilité)
#
#   catalogue_lot (dans l'app catalogue) :
#     - CHK_lot_quantite_disponible_pos     : quantite_disponible >= 0
#     - CHK_lot_quantite_initiale_pos       : quantite_initiale >= 0
#     - CHK_lot_prix_achat_positif          : prix_achat_unitaire >= 0
#
#   audit_journalaudit :
#     - IDX audit_type_cree_le_idx          : type_action, cree_le (reporting)
#     - IDX audit_utilisateur_cree_le_idx   : utilisateur, cree_le (revue par agent)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0005_rename_vente_statut_idx_ventes_vent_statut_5cc8a4_idx_and_more"),
    ]

    operations = [
        # ── ventes_vente : CHECK montants positifs ────────────────────────────
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.CheckConstraint(
                check=models.Q(montant_total__gte=0),
                name="chk_vente_montant_total_positif",
                violation_error_message="Le montant total d'une vente ne peut pas être négatif.",
            ),
        ),
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.CheckConstraint(
                check=models.Q(montant_encaisse__gte=0),
                name="chk_vente_montant_encaisse_positif",
                violation_error_message="Le montant encaissé ne peut pas être négatif.",
            ),
        ),
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.CheckConstraint(
                check=models.Q(montant_rendu__gte=0),
                name="chk_vente_montant_rendu_positif",
                violation_error_message="Le montant rendu ne peut pas être négatif.",
            ),
        ),
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.CheckConstraint(
                check=models.Q(sous_total__gte=0),
                name="chk_vente_sous_total_positif",
                violation_error_message="Le sous-total d'une vente ne peut pas être négatif.",
            ),
        ),
        # ── ventes_vente : index cree_le (clôture de caisse, rapports) ───────
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(fields=["cree_le"], name="ventes_vent_cree_le_idx"),
        ),
    ]
