# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produits_controles", "0002_registre_ligne_vente_reconciliation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="registreproduitcontrole",
            new_name="produits_co_medicam_129383_idx",
            old_name="pc_med_date_idx",
        ),
        migrations.RenameIndex(
            model_name="registreproduitcontrole",
            new_name="produits_co_type_mo_50ae1e_idx",
            old_name="pc_type_date_idx",
        ),
    ]
