# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="journalaudit",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="journalaudit",
            new_name="audit_journ_type_ac_a45a2a_idx",
            old_name="audit_type_date_idx",
        ),
        migrations.RenameIndex(
            model_name="journalaudit",
            new_name="audit_journ_utilisa_9cb49e_idx",
            old_name="audit_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="journalaudit",
            new_name="audit_journ_severit_c4b9f1_idx",
            old_name="audit_sev_date_idx",
        ),
        migrations.RenameIndex(
            model_name="journalaudit",
            new_name="audit_journ_cree_le_69a3c3_idx",
            old_name="audit_date_idx",
        ),
    ]
