# Generated by PharmApp ÉTAPE 02 — Index performance audit (2026-08-06)
#
# Le journal d'audit est interrogé intensément par les rapports réglementaires
# et la tâche verifier_integrite_audit. Ces deux index couvrent les requêtes
# les plus fréquentes identifiées lors de l'audit ÉTAPE 02.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_journalaudit_cree_le_explicite"),
    ]

    operations = [
        # ── Index de reporting : type_action + date ────────────────────────────
        migrations.AddIndex(
            model_name="journalaudit",
            index=models.Index(
                fields=["type_action", "cree_le"],
                name="audit_type_cree_le_idx",
            ),
        ),
        # ── Index de revue par agent : utilisateur + date ─────────────────────
        migrations.AddIndex(
            model_name="journalaudit",
            index=models.Index(
                fields=["utilisateur", "cree_le"],
                name="audit_utilisateur_cree_le_idx",
            ),
        ),
    ]
