# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("synchronisation", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conflitsynchronisation",
            new_name="synchronisa_statut_4bda29_idx",
            old_name="sync_statut_idx",
        ),
        migrations.RenameIndex(
            model_name="conflitsynchronisation",
            new_name="synchronisa_modele_1e774e_idx",
            old_name="sync_modele_obj_idx",
        ),
    ]
