# Generated by Django 5.0.8 on 2026-08-06 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronisation', '0002_rename_sync_statut_idx_synchronisa_statut_4bda29_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementSynchronisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_evenement', models.CharField(max_length=60, verbose_name="Type d'événement")),
                ('modele_source', models.CharField(max_length=60, verbose_name='Modèle source')),
                ('id_objet', models.CharField(max_length=64, verbose_name="Identifiant de l'objet")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=15)),
                ('charge_utile', models.JSONField(blank=True, default=dict)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement de synchronisation',
                'verbose_name_plural': 'Événements de synchronisation',
                'db_table': 'synchronisation_evenement',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['type_evenement', 'statut'], name='synchronisa_type_ev_17d548_idx'), models.Index(fields=['id_objet'], name='synchronisa_id_obje_2385a3_idx')],
            },
        ),
    ]
