# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametrage", "0002_compteur_numerotation"),
        ("parametrage", "0002_officine_parametrage_cloud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrage",
            name="format_numerotation",
            field=models.CharField(
                default="VTE-{YYYY}-{NNNN}",
                help_text="Gabarit de numérotation : {YYYY}=année, {MM}=mois, {NNNN}=séquence",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="parametrage",
            name="seuil_alerte_stock_jours",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Quantité minimale en unités déclenchant une alerte de stock bas",
            ),
        ),
        migrations.AlterField(
            model_name="parametrage",
            name="seuil_peremption_jours",
            field=models.PositiveIntegerField(
                default=60, help_text="Nombre de jours avant péremption déclenchant une alerte"
            ),
        ),
    ]
