# Generated by Django 5.0.8 on 2026-08-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametrage", "0003_alter_parametrage_format_numerotation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officineparametrage",
            name="cloud_api_url",
            field=models.URLField(
                blank=True, help_text="URL de base de l'API cloud (ex: https://cloud.pharmapp.bf)."
            ),
        ),
        migrations.AlterField(
            model_name="officineparametrage",
            name="version_logiciel",
            field=models.CharField(
                blank=True,
                help_text="Version du logiciel local (injectée depuis settings.py au démarrage).",
                max_length=20,
            ),
        ),
    ]
