# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordonnances", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ordonnance",
            new_name="ordonnances_client__248b18_idx",
            old_name="ord_client_statut_idx",
        ),
        migrations.RenameIndex(
            model_name="ordonnance",
            new_name="ordonnances_statut_992e89_idx",
            old_name="ord_statut_idx",
        ),
        migrations.AlterField(
            model_name="ordonnance",
            name="date_expiration",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date d'expiration (généralement 3 mois après prescription)",
            ),
        ),
    ]
