# Generated by PharmApp ÉTAPE 02 — Index ordonnances (2026-08-06)
#
# Pas de CHECK métier sur les ordonnances : les champs critiques sont soit
# des FK PROTECT, soit des BinaryField (chiffrés). On ajoute uniquement
# l'index manquant sur cree_le pour les purges automatiques.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordonnances", "0002_rename_ord_client_statut_idx_ordonnances_client__248b18_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ordonnance",
            index=models.Index(
                fields=["cree_le"],
                name="ordonnances_cree_le_idx",
            ),
        ),
        # Index sur prescripteur pour les audits ANRP (contrôle ordonnances
        # par médecin prescripteur sur une période)
        migrations.AddIndex(
            model_name="ordonnance",
            index=models.Index(
                fields=["date_prescription"],
                name="ord_date_prescription_idx",
            ),
        ),
    ]
