# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_credit_encours_et_contraintes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_telepho_8c69d9_idx",
            old_name="cli_tel_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_numero__3f5685_idx",
            old_name="cli_num_ass_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_est_act_1dcf98_idx",
            old_name="cli_actif_idx",
        ),
        migrations.AlterField(
            model_name="client",
            name="allergies",
            field=models.TextField(
                blank=True,
                help_text="Données médicales sensibles. Visibles uniquement par pharmacien_adjoint et supérieurs (§7.2 CDC). Un caissier ne doit JAMAIS voir ce champ — restriction appliquée côté serializer serveur, pas uniquement dans l'UI.",
                verbose_name="Allergies connues",
            ),
        ),
    ]
