# Generated by PharmApp ÉTAPE 02 — Durcissement contraintes clients (2026-08-06)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_rename_cli_tel_idx_clients_cli_telepho_8c69d9_idx_and_more"),
    ]

    operations = [
        # ── clients_client : CHECK plafond et taux ────────────────────────────
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                check=models.Q(plafond_credit__gte=0),
                name="chk_client_plafond_credit_positif",
                violation_error_message="Le plafond de crédit ne peut pas être négatif.",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                check=models.Q(taux_prise_en_charge__gte=0) & models.Q(taux_prise_en_charge__lte=100),
                name="chk_client_taux_prise_en_charge",
                violation_error_message="Le taux de prise en charge doit être compris entre 0 et 100 %.",
            ),
        ),
        # ── clients_client : index crédit actif (requêtes de plafond) ─────────
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["credit_autorise", "est_actif"],
                name="clients_encours_credit_idx",
            ),
        ),
    ]
