# Generated by Django 5.0.8 on 2026-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_medicament_prix_reglemente"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lot",
            new_name="catalogue_l_medicam_8a7259_idx",
            old_name="cat_lot_med_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="lot",
            new_name="catalogue_l_est_act_766110_idx",
            old_name="cat_lot_actif_idx",
        ),
        migrations.RenameIndex(
            model_name="lot",
            new_name="catalogue_l_date_pe_42120b_idx",
            old_name="cat_lot_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="medicament",
            new_name="catalogue_m_nom_8e0b1d_idx",
            old_name="cat_med_nom_idx",
        ),
        migrations.RenameIndex(
            model_name="medicament",
            new_name="catalogue_m_code_ci_b51ac0_idx",
            old_name="cat_med_cis_idx",
        ),
        migrations.RenameIndex(
            model_name="medicament",
            new_name="catalogue_m_est_act_5dce71_idx",
            old_name="cat_med_actif_idx",
        ),
        migrations.AddIndex(
            model_name="medicament",
            index=models.Index(fields=["code_barre"], name="catalogue_m_code_ba_a1b390_idx"),
        ),
    ]
