# Generated by PharmApp ÉTAPE 02 — Durcissement contraintes lots (2026-08-06)
# Les contraintes CHECK du modèle Lot appartiennent à l'app « catalogue »
# (propriétaire du modèle) : Django résout AddConstraint dans l'app_label de
# la migration, elles ne peuvent donc pas vivre dans une migration « stocks ».

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_rename_cat_lot_med_exp_idx_catalogue_l_medicam_8a7259_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.CheckConstraint(
                check=models.Q(quantite_disponible__gte=0),
                name="chk_lot_quantite_disponible_pos",
                violation_error_message="La quantité disponible d'un lot ne peut pas être négative.",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.CheckConstraint(
                check=models.Q(quantite_initiale__gte=0),
                name="chk_lot_quantite_initiale_pos",
                violation_error_message="La quantité initiale d'un lot ne peut pas être négative.",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.CheckConstraint(
                check=models.Q(prix_achat_unitaire__gte=0),
                name="chk_lot_prix_achat_positif",
                violation_error_message="Le prix d'achat unitaire ne peut pas être négatif.",
            ),
        ),
    ]
